import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import React from "react";
import Cards from "@/components/cards/Cards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dennis Germishuys</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>

        <div className={styles.description}>
          <p>
            A FullStack JS Developer
          </p>
          <div>
            <a
              href="https://www.linkedin.com/in/dennis-germishuys-6585811b9/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By Dennis Germishuys
              <Image
                src="/favicon.png"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={20}
                height={20}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.heading}>
            Your Next
            <span className={styles.developer} data-text={'Developer'}>Developer</span>
          </div>
        </div>

          <Cards />
      </main>
    </>
  )
}
